# Gemfile
# By Ron Bowes
#
# See LICENSE.md

source 'https://rubygems.org'

gem 'celluloid'     # hm
gem 'celluloid-dns' # dns
gem 'trollop'       # commandline parsing
gem 'rexec'         # this appears to be required sometimes; see https://github.com/iagox86/dnscat2/issues/65
